### ISSUE TITLE
Not possible to go through NPC

### ISSUE THREAD

**Issue by Vlek** [OrionUO/OrionUO#46]
[Copied over from Hotride/OrionUO](https://github.com/Hotride/OrionUO/issues/85)

[ 28:50 ] Not possible to go through NPC. It works with standard client. Polserver.
https://www.youtube.com/watch?v=zhetg7pQeKY

It is caused by wrong handling of configuration packet (UpdatePlayer) from server, which sets walk through for NPC on/off.

**Comment by VladislavVesely** [comment]
Yes. Byt i did not know how does this packet work on different servers or if it’s pol specific, so i did not commit that to master.

**Comment by fungos** [comment]
I tested in RunUO and didn't notice any difference with and without the check.
In anyway I just commented the check on the path finding code. I'll commit with this check removed.

**Comment by fungos** [comment]
Pushed the fix from @VladislavVesely. Looks ok.
