### ISSUE TITLE
HIDPI Screen issues

### ISSUE THREAD

**Issue by Nirad** [OrionUO/OrionUO#66]
When on HIDPI resolution i get this non HIDPI works good
<img width="1417" alt="capture d ecran le 2018-12-23 a 20 57 19" src="https://user-images.githubusercontent.com/359353/50389208-6dc6a580-06f5-11e9-8004-3879ccfe3d4d.png">

**Comment by Nirad** [comment]
If I remove SDL_WINDOW_ALLOW_HIGHDPI in WispWindows.cpp line 290 all is ok

**Comment by fungos** [comment]
Waiting for the PR :)
