### ISSUE TITLE
Client crashes on low hp mobs

### ISSUE THREAD

**Issue by baconmilk** [OrionUO/OrionUO#78]
* www.uooutlands.com

Bug happens when killing mobs and they start to run away on low hp. This happens on latest version of orion and the community version of outlands as well..

![screenshot_4](https://user-images.githubusercontent.com/6684273/50550514-a2e57180-0c7a-11e9-9b7c-0004cf103f52.png)
![screenshot_5](https://user-images.githubusercontent.com/6684273/50550515-a37e0800-0c7a-11e9-9a65-415244332d8c.png)
<img width="960" alt="screenshot_1" src="https://user-images.githubusercontent.com/6684273/50550783-ff4a9000-0c7e-11e9-86f1-0385e62e5f03.png">
<img width="960" alt="screenshot_2" src="https://user-images.githubusercontent.com/6684273/50550517-a37e0800-0c7a-11e9-8c9e-d8608093036e.png">
<img width="960" alt="screenshot_3" src="https://user-images.githubusercontent.com/6684273/50550518-a37e0800-0c7a-11e9-8ce3-f203651fd60c.png">

[crash_2018_12_30___21_21_47_849.txt](https://github.com/OrionUO/OrionUO/files/2717466/crash_2018_12_30___21_21_47_849.txt)
[crash_2018_12_30___21_14_42_753.txt](https://github.com/OrionUO/OrionUO/files/2717467/crash_2018_12_30___21_14_42_753.txt)
[crash_2018_12_30___21_19_5_343.txt](https://github.com/OrionUO/OrionUO/files/2717468/crash_2018_12_30___21_19_5_343.txt)

[uolog.txt](https://github.com/OrionUO/OrionUO/files/2717465/uolog.txt)

**Comment by fungos** [comment]
I played a lot the last days and couldn't reproduce this problem. Can you try without Orion Assistant so to confirm if this is a client issue or assistant?

**Comment by ZethSerB** [comment]
WithOut assist.
1 mob - OK
2 mob - lagging when it go away
3 mob - crash..
![without assist](https://user-images.githubusercontent.com/46327938/50606719-6068a280-0ecf-11e9-9cc4-252de662b103.png)

**Comment by ZethSerB** [comment]
[crash_2019_1_2___20_24_58_610.txt](https://github.com/OrionUO/OrionUO/files/2721577/crash_2019_1_2___20_24_58_610.txt)
